ministryofjustice/grc-app

- .circleci/config.yml
- grc/upload/__init__.py
- grc/utils/form_custom_validators.py
- tests/end_to_end_tests/journey_2/section_gov_uk_pay.py
Clean up extra logging and uncomment tests in build
> RST-5173 clean up redundant logs

- admin/applications/__init__.py
https://tools.hmcts.net/jira/browse/RST-5128
> RST-5128 query all apps by app status

- grc/personal_details/forms.py
- tests/end_to_end_tests/journey_1/personal_details/section.py
https://tools.hmcts.net/jira/browse/RST-5120
> Rst 5120 persistant data bug

- deploy/development/app-deployment.yaml
- deploy/development/ingress.yaml
- deploy/production/ingress.yaml
- deploy/staging/ingress.yaml
- requirements.txt
Add base OWASP Mod Security to ingress
https://tools.hmcts.net/jira/browse/RST-5119
> RST-5119 add modsec firewall

- dashboard/static/assets/charts.js
- dashboard/templates/stats/stats.html
https://tools.hmcts.net/jira/browse/RST-5129
> RST-5129 wait for js document to be ready before rendering chart

- .circleci/config.yml
- deploy/development/admin-deployment.yaml
- deploy/development/admin-service.yaml
- deploy/development/app-deployment.yaml
- deploy/development/app-service.yaml
- deploy/development/dashboard-deployment.yaml
- deploy/development/dashboard-service.yaml
- deploy/development/grc-clamav-deployment.yaml
- deploy/development/grc-clamav-service.yaml
- deploy/development/ingress.yaml
- deploy/development/secret.yaml
add deployment and service config for dev env
> RST-5182 add deployment and service config for dev env

- grc/utils/form_custom_validators.py
- tests/end_to_end_tests/journey_1/personal_details/section.py
- tests/helpers/e2e_page_helpers.py
https://tools.hmcts.net/jira/browse/RST-5456
Remove validation defined in [RST-5242](https://tools.hmcts.net/jira/browse/RST-5242) if the following:
Have you ever been issued a Gender Recognition Certificate (or its equivalent) in another country? = 'Yes' (Confirmation section)
> Rst 5456 dot validation change

- grc/templates/document-checker/your-documents.html
https://tools.hmcts.net/jira/browse/RST-5470
> RST-5470 change doc checker content

- admin/templates/applications/applications.html
https://tools.hmcts.net/jira/browse/RST-5453
> RST-5453 change admin tab from complete to completed

- admin/applications/__init__.py
- admin/static/assets/js/applications.js
- admin/templates/applications/applications.html
- admin/templates/base.html
https://tools.hmcts.net/jira/browse/RST-5452
> Rst 5452 mark multi apps as completed

- deploy/development/admin-deployment.yaml
- deploy/development/app-deployment.yaml
- deploy/development/dashboard-deployment.yaml
- deploy/production/admin-deployment.yaml
- deploy/production/app-deployment.yaml
- deploy/production/dashboard-deployment.yaml
- deploy/staging/admin-deployment.yaml
- deploy/staging/app-deployment.yaml
- deploy/staging/dashboard-deployment.yaml
https://tools.hmcts.net/jira/browse/RST-5657
> Rst 5657 zero downtime deployments

- .circleci/config.yml
https://tools.hmcts.net/jira/browse/RST-5893
> RST-5893 tag images with sha number

- grc/__init__.py
https://tools.hmcts.net/jira/browse/RST-5953
> RST-5953 make upload paths exempt to rate limiter

- deploy/development/ingress.yaml
- deploy/production/ingress.yaml
- deploy/staging/ingress.yaml
- grc/upload/__init__.py
https://tools.hmcts.net/jira/browse/RST-5581
> Rst 5581 upload modsec issue

- .circleci/config.yml
https://tools.hmcts.net/jira/browse/RST-6004
> RST-6004 add correct manifest path for maintenance pipleine

- admin/admin/__init__.py
- admin/password_reset/__init__.py
- grc/utils/date_utils.py
- grc/utils/form_custom_validators.py
- grc/utils/security_code.py
- grc/utils/session.py
https://tools.hmcts.net/jira/browse/RST-5961 - bypass security code if re logging in within 24 hours
https://tools.hmcts.net/jira/browse/RST-5974 - forgot password bug
> Rst 5974 admin login bug

- Dockerfile
- admin.Dockerfile
- dashboard.Dockerfile
https://tools.hmcts.net/jira/browse/RST-6006
> RST-6006 update node distro in images

- deploy/production/ingress-admin.yaml
- deploy/production/ingress.yaml
- deploy/staging/ingress-admin.yaml
- deploy/staging/ingress.yaml
https://tools.hmcts.net/jira/browse/RST-6207
> RST-6207 make dashbaord portal only visible via vpn

- .circleci/config.yml
https://tools.hmcts.net/jira/browse/RST-6399
> RST-6399 fix e2e 2 test

- dashboard/stats/__init__.py
https://tools.hmcts.net/jira/browse/RST-6447
> RST 6447 fix dashboard bug

- admin/password_reset/forms.py
- grc/utils/form_custom_validators.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_password_strength.py
https://tools.hmcts.net/jira/browse/RST-6460
> RST-6460 write ut for validator password and refactor

- .circleci/config.yml
https://tools.hmcts.net/jira/browse/RST-6471
> Rst 6471 code coverage report

- tests/grc/unit/utils/test_custom_form_validators/test_validate_date_range_form.py
https://tools.hmcts.net/jira/browse/RST-6476
> RST 6476 add ut for validate date range form

- tests/grc/unit/utils/test_custom_form_validators/test_validate_date_ranges.py
https://tools.hmcts.net/jira/browse/RST-6480
> RST 6476 add ut for validate date ranges

- grc/personal_details/forms.py
- grc/utils/form_custom_validators.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_national_insurance_number.py
https://tools.hmcts.net/jira/browse/RST-6472
> Rst 6472 ut validate national insurance number

- grc/personal_details/forms.py
- grc/utils/form_custom_validators.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_phone_number.py
https://tools.hmcts.net/jira/browse/RST-6473
> Rst 6473 ut validate phone number

- grc/personal_details/forms.py
- grc/utils/form_custom_validators.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_date_of_transiton.py
https://tools.hmcts.net/jira/browse/RST-6464
> RST-6464 add ut and refactor transition date validator

- grc/personal_details/forms.py
- grc/utils/form_custom_validators.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_statutory_declaration_date.py
https://tools.hmcts.net/jira/browse/RST-6466
> RST-6466 add ut and slight refactor for stat dec validator

- grc/submit_and_pay/forms.py
- grc/utils/form_custom_validators.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_hwf_reference_number.py
https://tools.hmcts.net/jira/browse/RST-6474
> Rst 6474 ut validate hwf reference number

- grc/utils/form_custom_validators.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_single_date.py
https://tools.hmcts.net/jira/browse/RST-6475
> Rst 6475 ut validate single date

- admin/tools/forms.py
- grc/upload/forms.py
- grc/utils/form_custom_validators.py
- tests/grc/unit/conftest.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_multi_files_allowed.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_single_file_allowed.py
https://tools.hmcts.net/jira/browse/RST-6481
> Rst 6481 ut multi file allowed

- admin/tools/forms.py
- grc/upload/forms.py
- grc/utils/form_custom_validators.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_file_size_limit.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_multiple_files_size_limit.py
https://tools.hmcts.net/jira/browse/RST-6484
> Rst 6484 ut file size limit

- admin/tools/forms.py
- grc/config.py
- grc/upload/forms.py
- grc/utils/form_custom_validators.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_file_virus_scan.py
https://tools.hmcts.net/jira/browse/RST-6487
> Rst 6487 ut file virus scan

- grc/sass/app.scss
- package-lock.json
- package.json
https://tools.hmcts.net/jira/browse/RST-6525
> RST-6525 revert gov frontend upgrade changes

- grc/translations/cy/LC_MESSAGES/messages.po
https://tools.hmcts.net/jira/browse/RST-6563
> RST-6563 swap welsh trans for yes and no

- admin/applications/__init__.py
- grc/submit_and_pay/__init__.py
- grc/utils/application_files.py
- tests/grc/unit/utils/test_application_files/test_create_or_download_pdf.py
https://tools.hmcts.net/jira/browse/RST-6579
> Rst 6579 ut application files 2

- admin/templates/govuk-design-system-templates/continue.html
- dashboard/templates/govuk-design-system-templates/continue.html
- grc/personal_details/constants.py
- grc/personal_details/forms.py
- grc/templates/govuk-design-system-templates/continue.html
- grc/templates/personal-details/name.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
- tests/end_to_end_tests/journey_cy/data.py
- tests/end_to_end_tests/journey_cy/personal_details/section.py
- tests/end_to_end_tests/journey_cy/test_e2e_journey_cy.py
https://tools.hmcts.net/jira/browse/RST-6567
> Rst 6567 welsh pers details name

- grc/business_logic/constants.py
- grc/personal_details/constants.py
- grc/personal_details/forms.py
- grc/templates/personal-details/hmrc.html
- grc/translations/cy/LC_MESSAGES/messages.po
- grc/utils/form_custom_validators.py
- messages.pot
- tests/end_to_end_tests/journey_cy/data.py
- tests/end_to_end_tests/journey_cy/personal_details/section.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_national_insurance_number.py
https://tools.hmcts.net/jira/browse/RST-6610
> Rst 6610 welsh pers dets hmrc

- grc/partnership_details/forms.py
- grc/templates/partnership-details/current-check.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
- tests/end_to_end_tests/journey_cy/partnership_details/section.py
- tests/end_to_end_tests/journey_cy/test_e2e_journey_cy.py
https://tools.hmcts.net/jira/browse/RST-6619
> Rst 6618 welsh part dets index

- grc/__init__.py
- grc/partnership_details/__init__.py
- grc/partnership_details/constants.py
- grc/partnership_details/forms.py
- grc/templates/partnership-details/stay-together.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
- tests/end_to_end_tests/journey_cy/partnership_details/section.py
https://tools.hmcts.net/jira/browse/RST-6620
> Rst 6620 welsh part dets stay married

- grc/templates/base.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
- tests/end_to_end_tests/journey_cy/login_and_confirmation/section.py
https://tools.hmcts.net/jira/browse/RST-6634
> Rst 6634 welsh start app missing

- grc/templates/upload/_upload-files-section.html
- grc/templates/upload/evidence.html
- grc/templates/upload/medical-reports.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
https://tools.hmcts.net/jira/browse/RST-6636
> Rst 6636 welsh uploads gender evidence

- grc/templates/upload/marriage-documents.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
- tests/end_to_end_tests/journey_cy/login_and_confirmation/section.py
- tests/end_to_end_tests/journey_cy/uploads/page_marriage_documents.py
- tests/end_to_end_tests/journey_cy/uploads/page_overseas_documents.py
- tests/end_to_end_tests/journey_cy/uploads/section.py
https://tools.hmcts.net/jira/browse/RST-6640
> Rst 6640 welsh uploads marriage

- grc/templates/upload/name-change.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
- tests/end_to_end_tests/journey_cy/uploads/page_marriage_documents.py
- tests/end_to_end_tests/journey_cy/uploads/page_name_change_documents.py
- tests/end_to_end_tests/journey_cy/uploads/page_statutory_declarations.py
- tests/end_to_end_tests/journey_cy/uploads/section.py
https://tools.hmcts.net/jira/browse/RST-6642
> Rst 6642 welsh uploads name change

- grc/submit_and_pay/constants.py
- grc/submit_and_pay/forms.py
- grc/templates/submit-and-pay/method.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
- tests/end_to_end_tests/journey_cy/submit_and_pay/section.py
- tests/end_to_end_tests/journey_cy/test_e2e_journey_cy.py
https://tools.hmcts.net/jira/browse/RST-6645
> Rst 6645 welsh subpay index

- grc/submit_and_pay/constants.py
- grc/templates/document-checker/email-sent.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
https://tools.hmcts.net/jira/browse/RST-6653
> RST-6653 translate email sent doc checker page

- grc/templates/contact-admin.html
- grc/templates/custom-error-templates/404.html
- grc/templates/start-application/application-already-submitted.html
- grc/templates/submit-and-pay/confirmation.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
https://tools.hmcts.net/jira/browse/RST-6665
> Rst 6665 welsh 404 page

- grc/__init__.py
- grc/templates/custom-error-templates/503.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
https://tools.hmcts.net/jira/browse/RST-6672
> Rst 6672 welsh 503

- grc/__init__.py
- grc/templates/custom-error-templates/error-default.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
https://tools.hmcts.net/jira/browse/RST-6673
> RST 6673 translate content default error page

- grc/save_and_return/__init__.py
- grc/templates/save-and-return/exit-application.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
- tests/end_to_end_tests/journey_1/login_and_confirmation/section.py
https://tools.hmcts.net/jira/browse/RST-6676
> Rst 6676 welsh save exit

- grc/business_logic/constants/feedback.py
- grc/feedback/__init__.py
- grc/feedback/forms.py
- grc/templates/feedback/feedback-form.html
- grc/templates/feedback/feedback-received.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
https://tools.hmcts.net/jira/browse/RST-6679
> Rst 6679 welsh feedback

- grc/templates/birth-registration/forces.html
- tests/grc/integration/birth_registration/test_adopted.py
- tests/grc/integration/birth_registration/test_adopted_uk.py
- tests/grc/integration/birth_registration/test_check_your_answers.py
- tests/grc/integration/birth_registration/test_country.py
- tests/grc/integration/birth_registration/test_dob.py
- tests/grc/integration/birth_registration/test_fathers_name.py
- tests/grc/integration/birth_registration/test_fathers_name_check.py
- tests/grc/integration/birth_registration/test_forces.py
- tests/grc/integration/birth_registration/test_index.py
- tests/grc/integration/birth_registration/test_mothers_name.py
- tests/grc/integration/birth_registration/test_place_of_birth.py
- tests/grc/integration/birth_registration/test_uk_check.py
https://tools.hmcts.net/jira/browse/RST-6699
> RST-6699 it birth reg section

- grc/translations/cy/LC_MESSAGES/messages.po
- tests/end_to_end_tests/journey_cy/submit_and_pay/section.py
https://tools.hmcts.net/jira/browse/RST-6737
> Rst 6737 welsh amendments

- deploy/production/ingress-admin.yaml
- deploy/staging/ingress-admin.yaml
- deploy/staging/ingress.yaml
https://tools.hmcts.net/jira/browse/RST-6753
> RST-6753 fix admin restricted access

- grc/utils/security_code.py
- tests/grc/unit/utils/test_security_code/test_security_code.py
https://tools.hmcts.net/jira/browse/RST-6775
> Rst 6775 security duplication fix

- grc/translations/cy/LC_MESSAGES/messages.po
https://tools.hmcts.net/jira/browse/RST-6790
> RST-6790 update welsh for new countries

- dashboard/__init__.py
https://tools.hmcts.net/jira/browse/RST-6812
> RST-6812 init babel app for dashboard

- admin/__init__.py
https://tools.hmcts.net/jira/browse/RST-6813
> RST-6813 setup babel app for admin

- .circleci/config.yml
- deploy/staging/ingress-admin.yaml
- deploy/staging/ingress.yaml
- grc/static/application.js
- grc/templates/base.html
- grc/templates/document-checker/doc-checker-base.html
https://tools.hmcts.net/jira/browse/RST-6479
> RST-6479 add new google tag base templates

- dashboard/stats/__init__.py
- grc/utils/form_custom_validators.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_date_range.py
Edited date range validation to add more meaningful error messages. Added new tests for the new errors.
> RST-6495 More meaningful error messages

- dashboard/__init__.py
- dashboard/config.py
- tests/grc/unit/conftest.py
- tests/grc/unit/utils/test_custom_form_validators/test_validate_date_range.py
Fixed the commented out test by creating a POST request to test the error message.
> RST-6893 - Added test for an end date > today

- migrations/env.py
https://tools.hmcts.net/jira/browse/RST-6943
> RST-6943 package upgrades and resolved bugs from upgrades

- grc/upload/__init__.py
https://tools.hmcts.net/jira/browse/RST-6966
> Resolving double download error issue on Admin

- tests/end_to_end_tests/journey_1/data.py
- tests/end_to_end_tests/journey_1/submit_and_pay/section.py
- tests/end_to_end_tests/journey_cy/data.py
https://tools.hmcts.net/jira/browse/RST-6953
> Rst 6953 fix e2e tests

- admin/__init__.py
- admin/static/assets/js/applications.js
- admin/templates/applications/applications.html
- admin/templates/applications/view-application.html
- grc/__init__.py
- grc/mock_api/__init__.py
- tests/end_to_end_tests/journey_2/section_gov_uk_pay.py
https://tools.hmcts.net/jira/browse/RST-6991
> Rst 6991 glimr select applications

- grc/submit_and_pay/__init__.py
- grc/templates/submit-and-pay/method.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
https://tools.hmcts.net/jira/browse/RST-7286
> RST-7286 Change payment from 5 to 6 pounds

- admin/glimr/glimr_new_case.py
- admin/static/assets/js/applications.js
- admin/templates/applications/applications-error.html
- admin/templates/applications/applications.html
- tests/end_to_end_tests/accessibility/accessibility_checks.py
- tests/end_to_end_tests/journey_admin/applications_glimr/section.py
- tests/end_to_end_tests/journey_admin/login_and_confirmation/section.py
https://tools.hmcts.net/jira/browse/RST-7292
> RST 7292 Error Handling

- deploy/production/ingress-admin.yaml
- deploy/staging/ingress-admin.yaml
By pass deployment to staging due to ongoing glimr testing
> Add the 128 address to admin ingress to handle more MOJO devices

- .circleci/config.yml
- deploy/uat/admin-deployment.yaml
- deploy/uat/admin-service.yaml
- deploy/uat/app-deployment.yaml
- deploy/uat/app-service.yaml
- deploy/uat/dashboard-deployment.yaml
- deploy/uat/dashboard-service.yaml
- deploy/uat/grc-clamav-deployment.yaml
- deploy/uat/grc-clamav-service.yaml
- deploy/uat/ingress-admin.yaml
- deploy/uat/ingress.yaml
- deploy/uat/jobs/anonymise-expired-applications.yaml
- deploy/uat/jobs/delete-completed-applications.yaml
- deploy/uat/jobs/delete-expired-security-codes.yaml
- deploy/uat/jobs/notify-applicants-inactive-applications.yaml
- deploy/uat/maintenance/maintenance-deployment.yaml
- deploy/uat/maintenance/maintenance-service.yaml
Create uat environment for glimr to be tested on
> Create uat environment for glimr

- grc/business_logic/constants/one_login.py
- grc/one_login/__init__.py
- grc/one_login/forms.py
- grc/start_application/__init__.py
- grc/templates/one-login/identityEligibility.html
- grc/translations/cy/LC_MESSAGES/messages.po
- messages.pot
> RST 7463 - Change content to identity eligibility 

- grc/business_logic/data_structures/application_data.py
- grc/business_logic/data_structures/uploads_data.py
- grc/templates/submit-and-pay/check-your-answers.html
- grc/templates/task-list.html
- grc/templates/upload/_upload-files-section.html
- grc/templates/upload/birth-or-adoption-certificate.html
- grc/upload/__init__.py
https://tools.hmcts.net/jira/browse/RST-7464
> RST 7464 enable birth certificate upload

- admin/templates/applications/application-pdfkit.html
- admin/templates/applications/application.html
- admin/templates/applications/view-application.html
- grc/templates/applications/application.html
- grc/templates/applications/application_user-pdfkit.html
- grc/templates/applications/application_user.html
- grc/utils/application_files.py
https://tools.hmcts.net/jira/browse/RST-7467
> RST-7467 enable download of birth certificate

- grc/templates/one-login/start.html
https://tools.hmcts.net/jira/browse/RST-7290
> RST-7290 test text

- deploy/production/ingress-admin.yaml
- deploy/production/ingress.yaml
To be merged on Monday morning 1/9/25 so that the OneLogin upgrade can take place
> Put all 3 portals in maintenance mode ready for upgrade
